M48
; DRILL file {KiCad (6.0.7)} date Thu 29 Sep 2022 09:15:44 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-29T21:15:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X4.901Y-4.7229
X5.1286Y-4.7229
T2
X4.2313Y-4.314
T3
X4.4281Y-4.314
T4
X4.1831Y-4.8091
X4.189Y-3.0787
X5.7067Y-4.8209
X5.7126Y-3.0768
T0
M30
